import streamlit as st
import pandas as pd
import numpy as np

st.subheader("Penerapan")
st.write("Penerapan cyber security terbagi menjadi tiga jenis, yaitu cloud security, network security, dan application security.")

st.subheader("Cloud Security")
st.write("Cloud security mengacu pada upaya individu atau kelompok dalam melindungi data yang tersimpan di cloud. Upaya perlindungan ini melibatkan teknologi, kebijakan kontrol dan layanan yang mendukung terciptanya keamanan cloud. Bagi penyedia layanan cloud storage, cloud security adalah aspek penting dalam upaya memastikan keamanan data. Pasalnya, untuk menyimpan data sensitif pelanggan, penyedia layanan cloud harus memenuhi persyaratan dan prosedur kemanan. Ancaman cloud security adalah penyalahgunaan data, pencurian data dan pembajakan traffic layanan. Penyedia layanan penyimpanan cloud yang buruk juga bisa mengancam kemanan cloud. Upaya penerapan cloud security bisa dilakukan dengan menggunakan firewall,  two factor authentication, VPN hingga enkripsi data.")

st.subheader("Network Security")
st.write("Network security adalah praktik perlindungan jaringan internal Anda dengan meningkatkan keamanan jaringan. Network security sangat penting terutama bagi perusahaan yang menggunakan sistem jaringan dalam aktivitasnya. Network security berguna untuk melindungi aset perusahaan dari ancaman cyber crime. Selain itu, perlindungan jaringan membuat pengelolaan lalu-lintas jaringan lebih efisien. Contoh umum network security adalah penggunaan antivirus dan firewall. Upaya ini dilakukan untuk mendeteksi ancaman yang muncul dari malware. Selain itu, Anda dapat menggunakan two factor authentication dan mengganti password secara berkala.")

st.subheader("Application Security")
st.write("Application security adalah usaha melindungi dan meningkatkan keamanan aplikasi dari ancaman yang mungkin terjadi. Dalam website toko online misalnya. Anda perlu meningkatkan keamanan website untuk memastikan data Anda dan pelanggan aman dari ancaman peretas. Cara pertama yang bisa dilakukan adalah autentikasi. Prosedur otentikasi memastikan hanya pengguna resmi yang dapat mengakses aplikasi. Misalnya permintaan username dan password pengguna. Selain itu terdapat autentikasi dua faktor. Sistem memberikan akses masuk kepada pengguna setelah menyelesaikan dua bentuk autentikasi. Yang pertama biasanya berupa username dan password. Bentuk kedua autentikasi bisa berupa kode yang dikirim ke ponsel, sidik jari, hingga pengenalan wajah. Cara kedua adalah otorisasi, atau pemberian wewenang. Otorisasi hanya bisa terjadi setelah proses autentikasi berhasil. Sistem akan mengecek sejauh mana kewenangan pengguna dalam menggunakan aplikasi. Selanjutnya adalah enkripsi. Dengan enkripsi, data sensitif pengguna aplikasi tidak akan bisa dibaca oleh pelaku kejahatan cyber. Besarnya arus lalu-lintas data di internet membuat enkripsi data menjadi salah satu cara menghindari ancaman cyber. Berikutnya adalah logging, yaitu perekaman informasi dan aktivitas dalam sebuah sistem. Logging juga merekam informasi siapa saja yang berusaha mengakses sebuah aplikasi. Terakhir adalah uji keamanan aplikasi. Ini adalah proses untuk memastikan semua proses keamanan berfungsi dengan baik.")